FROM nvidia/cuda:12.4.1-runtime-ubuntu22.04
WORKDIR /app
RUN apt-get update && apt-get install -y python3 python3-pip && rm -rf /var/lib/apt/lists/*
COPY . /app
RUN pip3 install --no-cache-dir -e .
CMD ["python3", "-m", "hshub.app"]
